version: '3.9'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: teste_kanastra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    restart: always

  backend:
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    depends_on:
      - database
    restart: always
